image: golang
workspace:
  base: /go
  path: src/github.com/drone/drone
script:
  - go get github.com/tools/godep
  - godep restore
  - go install github.com/panduroab/taskmanager
commands:
  - /go/bin/taskmanager
