workspace:
  base: /go
  path: src/github.com/drone/drone

build:
  image: golang:1.6
  environment:
    - GOPATH=/go
  commands:
    - go get github.com/tools/godep
    - godep restore
    - go install github.com/panduroab/taskmanager

publish:
  coverage:
    when:
      branch: master
